# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attributes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=b'database/covers'),
        ),
        migrations.AlterField(
            model_name='book',
            name='epub_file',
            field=models.FileField(blank=True, null=True, upload_to=b'database/books', verbose_name=b'EPUB File'),
        ),
        migrations.AlterField(
            model_name='book',
            name='mobi_file',
            field=models.FileField(blank=True, null=True, upload_to=b'database/books', verbose_name=b'MOBI File'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=b'database/books', verbose_name=b'PDF File'),
        ),
    ]
