# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attributes', '0050_auto_20160305_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=b'/home/fadi/Projects/_ebookify/database/covers'),
        ),
        migrations.AlterField(
            model_name='book',
            name='epub_file',
            field=models.FileField(blank=True, null=True, upload_to=b'/home/fadi/Projects/_ebookify/database/books', verbose_name=b'EPUB File'),
        ),
        migrations.AlterField(
            model_name='book',
            name='mobi_file',
            field=models.FileField(blank=True, null=True, upload_to=b'/home/fadi/Projects/_ebookify/database/books', verbose_name=b'MOBI File'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=b'/home/fadi/Projects/_ebookify/database/books', verbose_name=b'PDF File'),
        ),
    ]
